name: Build and Deploy Transfer Market API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

permissions:
  packages: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      latest_sha: ${{steps.getsha.outputs.latest_sha}}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "felipeall/transfermarkt-api"
          path: './transfermarket-api'
      
      - name: 'Get SHA'
        id: getsha
        working-directory: "./transfermarket-api"        
        run: | 
            latest_sha=$(git rev-parse HEAD)
            echo "Output [$latest_sha]"
            echo "latest_sha=$latest_sha" >> $GITHUB_OUTPUT 
      
      - name: 'Check if build is required or not'
        id: check
        working-directory: "./transfermarket-api"
        run: |
            latest_sha=$(git rev-parse HEAD)
            # Compare the provided SHA with the latest SHA and confirm whether build is required
            if [ "${{vars.LATEST_SHA}}" = "$latest_sha" ]; then
                echo "true=$isBuild" >> $GITHUB_OUTPUT    
            else
                echo "true=$isBuild" >> $GITHUB_OUTPUT
            fi
      
      - name: Set up QEMU
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        uses: docker/setup-buildx-action@v3
          
      - name: 'Login to GitHub Container Registry'
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker Image
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        working-directory: "./transfermarket-api"
        run: | 
            docker build . -t "ghcr.io/globall-connect/transfermarketapi:${{steps.getsha.outputs.latest_sha}}" -t "ghcr.io/globall-connect/transfermarketapi:latest"
      - name: Push Docker Image
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        working-directory: "./transfermarket-api"
        run: | 
            docker push "ghcr.io/globall-connect/transfermarketapi:${{steps.getsha.outputs.latest_sha}}"
            docker push "ghcr.io/globall-connect/transfermarketapi:latest"
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'production'
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: 'transfermarketapi'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/globall-connect/transfermarketapi:latest'
      - name: 'Update Commit Hash'
        run: |
          gh variable set LATEST_SHA --body "${{ needs.build.outputs.latest_sha }}"
        env:
          GH_TOKEN: ${{secrets.COMMIT_UPDATE_SECRET}}
      
