name: Build and Deploy Transfer Market API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "felipeall/transfermarkt-api"
          path: './transfermarket-api'
      
      - name: 'Get SHA'
        id: getsha
        working-directory: "./transfermarket-api"        
        run: | 
            latest_sha=$(git rev-parse HEAD)
            echo "Output [$latest_sha]"
            echo "latest_sha=$latest_sha" >> $GITHUB_OUTPUT 
      
      - name: 'Check if build is required or not'
        id: check
        working-directory: "./transfermarket-api"
        run: |
            latest_sha=$(git rev-parse HEAD)
            # Compare the provided SHA with the latest SHA and confirm whether build is required
            if [ "${{vars.LATEST_SHA}}" = "$latest_sha" ]; then
                echo "true=$isBuild" >> $GITHUB_OUTPUT    
            else
                echo "true=$isBuild" >> $GITHUB_OUTPUT
            fi
      
      - name: Set up QEMU
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        uses: docker/setup-buildx-action@v3
          
      - name: 'Login to GitHub Container Registry'
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.DOCKER_TOKEN}}

      - name: Build Docker Image
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        working-directory: "./transfermarket-api"
        run: | 
            docker build . -t "ghcr.io/GloBall-Connect/transfermarktapi:${{steps.getsha.outputs.latest_sha}} -t ghcr.io/GloBall-Connect/transfermarktapi:latest"
      - name: Push Docker Image
        if: ${{ steps.check.outputs.isBuild }} == 'true'
        working-directory: "./transfermarket-api"
        run: | 
            docker push "ghcr.io/GloBall-Connect/transfermarktapi:${{steps.getsha.outputs.latest_sha}} -t ghcr.io/GloBall-Connect/transfermarktapi:latest"
 