name: Build and Deploy Transfer Market API

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

permissions:
  packages: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      latest_sha: ${{steps.getsha.outputs.latest_sha}}
      deploy: ${{steps.check.outputs.latest_sha}}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "felipeall/transfermarkt-api"
          path: './transfermarket-api'
      
      - name: 'Get SHA'
        id: getsha
        working-directory: "./transfermarket-api"        
        run: | 
            latest_sha=$(git rev-parse HEAD)
            echo "Output [$latest_sha]"
            echo "latest_sha=$latest_sha" >> $GITHUB_OUTPUT 
      
      - name: 'Get Latest Commit SHA'
        id: check
        working-directory: "./transfermarket-api"
        run: |
            latest_sha=$(git rev-parse HEAD)
            echo "Output [$latest_sha]"
            echo "latest_sha=$latest_sha" >> $GITHUB_OUTPUT 
      - name: Set up QEMU
        if: ${{ steps.getsha.outputs.latest_sha != steps.check.outputs.latest_sha }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ steps.getsha.outputs.latest_sha != steps.check.outputs.latest_sha }}
        uses: docker/setup-buildx-action@v3
          
      - name: 'Login to GitHub Container Registry'
        if: ${{ steps.getsha.outputs.latest_sha != steps.check.outputs.latest_sha }}
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Docker Image
        if: ${{ steps.getsha.outputs.latest_sha != steps.check.outputs.latest_sha }}
        working-directory: "./transfermarket-api"
        run: | 
            docker build . -t "ghcr.io/globall-connect/transfermarketapi:${{steps.getsha.outputs.latest_sha}}" -t "ghcr.io/globall-connect/transfermarketapi:latest"
      - name: Push Docker Image
        if: ${{ steps.getsha.outputs.latest_sha != steps.check.outputs.latest_sha }}
        working-directory: "./transfermarket-api"
        run: | 
            docker push "ghcr.io/globall-connect/transfermarketapi:${{steps.getsha.outputs.latest_sha}}"
            docker push "ghcr.io/globall-connect/transfermarketapi:latest"
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.latest_sha != needs.build.outputs.deploy }}
    environment: 
      name: 'production'
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
        with:
          app-name: 'transfermarketapi'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/globall-connect/transfermarketapi:latest'
      - uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
            name: 'LATEST_SHA'
            value: '${{ needs.build.outputs.latest_sha }}'
            repository: globall-connect/transfermarktapi
            token: ${{ secrets.COMMIT_UPDATE_SECRET }}